# This is a basic workflow that is manually triggered

name: Refresh Playlist

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        default: 'World'
        required: true
        type: string

jobs:
  refresh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Refresh playlist
        run: |
          node scripts/generate-preset-playlist.mjs "${{ github.event.inputs.name }}"
          echo "Playlist aktualisiert für: ${{ github.event.inputs.name }}"
